// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdqFoIVxN22vjsSEmyIO0Zu9JESIsSBTk',
    appId: '1:600867017281:web:534a47cec6e2c39876acc0',
    messagingSenderId: '600867017281',
    projectId: 'notificacionesconfcm',
    authDomain: 'notificacionesconfcm.firebaseapp.com',
    storageBucket: 'notificacionesconfcm.firebasestorage.app',
    measurementId: 'G-HGVXEDN2GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJw0Z8AIx3BKAIi4gx59hyCjDVYDJYz20',
    appId: '1:600867017281:android:80cde5613b0269a776acc0',
    messagingSenderId: '600867017281',
    projectId: 'notificacionesconfcm',
    storageBucket: 'notificacionesconfcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZcGd4L7Aladb12ZFBK1-8g5IPvuDji28',
    appId: '1:600867017281:ios:01095ac69b83f13376acc0',
    messagingSenderId: '600867017281',
    projectId: 'notificacionesconfcm',
    storageBucket: 'notificacionesconfcm.firebasestorage.app',
    iosBundleId: 'com.example.actRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZcGd4L7Aladb12ZFBK1-8g5IPvuDji28',
    appId: '1:600867017281:ios:01095ac69b83f13376acc0',
    messagingSenderId: '600867017281',
    projectId: 'notificacionesconfcm',
    storageBucket: 'notificacionesconfcm.firebasestorage.app',
    iosBundleId: 'com.example.actRiverpod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdqFoIVxN22vjsSEmyIO0Zu9JESIsSBTk',
    appId: '1:600867017281:web:724247029837921e76acc0',
    messagingSenderId: '600867017281',
    projectId: 'notificacionesconfcm',
    authDomain: 'notificacionesconfcm.firebaseapp.com',
    storageBucket: 'notificacionesconfcm.firebasestorage.app',
    measurementId: 'G-JT7E665KDJ',
  );
}
